prompt --application/shared_components/user_interface/lovs/p242_chequeno
begin
--   Manifest
--     P242_CHEQUENO
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2026.03.30'
,p_release=>'26.1.2'
,p_default_workspace_id=>4744311978888504
,p_default_application_id=>107
,p_default_id_offset=>9480203831466364
,p_default_owner=>'IMART'
);
wwv_flow_imp_shared.create_list_of_values(
 p_id=>wwv_flow_imp.id(455251693252950424)
,p_lov_name=>'P242_CHEQUENO'
,p_static_id=>'p242-chequeno'
,p_lov_query=>wwv_flow_string.join(wwv_flow_t_varchar2(
'Select',
'b.ChequeNo d,',
'b.ChequeNo r',
'From ChequeBookIssue a, ChequeBookIssueDetail b, BossUser c,',
'DocumentStatusDetail dsd',
'Where a.Tno=b.Tno',
'and a.Tno=dsd.ModuleTno(+)',
'and dsd.DocumentStatusCode=''ACTIVE''',
'and a.BossUserCode=c.BossUserCode',
'and c.LoginName=:GLOBAL_LOGINNAME',
'and not exists(Select 1 ',
'	       From RtgsLetter aa',
'	       Where aa.ChequeNo=b.ChequeNo',
'		   and aa.Creator=c.LoginName',
'	      )',
'and not exists(',
'		select',
'			aa.TNO',
'		from LoanSanction aa',
'		where aa.CreditAccountCode = :P242_AccountCode',
'			and aa.MoneyTransferModeCode in (''CH'', ''CHEQUE'')',
'			and aa.MONEYTRANSFERREFERENCENO = b.ChequeNO',
'			and aa.MONEYTRANSFERREFERENCENO  is not null',
'	)',
'		',
'	and not exists(',
'		select',
'			aa.TNO',
'		from PaymentAdvice aa',
'		where aa.AccountCode = :P242_AccountCode',
'			and aa.MoneyTransferModeCode in (''CH'', ''CHEQUE'')',
'			and aa.MONEYTRANSFERREFERENCENO = b.ChequeNO',
'			and aa.MONEYTRANSFERREFERENCENO  is not null',
'	)',
'		',
'	and not exists(',
'		select',
'			aa.TNO',
'		from Challan aa',
'		where aa.AccountCode = :P242_AccountCode',
'			and aa.MoneyTransferModeCode in (''CH'', ''CHEQUE'')',
'			and aa.MONEYTRANSFERREFERENCENO = b.ChequeNO',
'			and aa.MONEYTRANSFERREFERENCENO  is not null',
'	)		',
'	/*and not exists(',
'		select',
'			aa.TNO',
'		from TDSChallanDetail aa',
'		where aa.AccountCode = :P242_AccountCode',
'			and aa.MoneyTransferModeCode in (''CH'', ''CHEQUE'')',
'			and aa.MONEYTRANSFERREFERENCENO = b.ChequeNO',
'			and aa.MONEYTRANSFERREFERENCENO  is not null',
'	)			',
'	*/',
'	and not exists(',
'		select',
'			aa.TNO',
'		from FreightAdvice aa',
'		where aa.CreditAccountCode = :P242_AccountCode',
'			and nvl(aa.MoneyTransferModeCode, ''fd23S'') in (''CH'', ''CHEQUE'')',
'			and aa.MONEYTRANSFERREFERENCENO = b.ChequeNO',
'			and aa.MONEYTRANSFERREFERENCENO  is not null',
'	)	',
'and a.LocationCode=:P242_LocationCode',
'UNION ALL',
'Select',
'b.ChequeNo d,',
'b.ChequeNo r',
'From ChequeReceipt a, ChequeReceiptDetail b, DocumentStatusDetail dsd',
'where a.Tno=b.Tno',
'and a.Tno=dsd.ModuleTno',
'and dsd.DocumentStatusCode=''ACTIVE''',
'and a.Creator=User',
'and not exists(Select 1 ',
'	       From RtgsLetter aa',
'	       Where aa.ChequeNo=b.ChequeNo',
'          		and aa.Creator=User',
'	      )',
'and not exists(',
'		select',
'			aa.TNO',
'		from LoanSanction aa',
'		where aa.CreditAccountCode = :P242_AccountCode',
'			and aa.MoneyTransferModeCode in (''CH'', ''CHEQUE'')',
'			and aa.MONEYTRANSFERREFERENCENO = b.ChequeNO',
'			and aa.MONEYTRANSFERREFERENCENO  is not null',
'	)',
'	',
'	and not exists(',
'		select',
'			aa.TNO',
'		from PaymentAdvice aa',
'		where aa.AccountCode = :P242_AccountCode',
'			and aa.MoneyTransferModeCode in (''CH'', ''CHEQUE'')',
'			and aa.MONEYTRANSFERREFERENCENO = b.ChequeNO',
'			and aa.MONEYTRANSFERREFERENCENO  is not null',
'	)',
'	',
'	and not exists(',
'		select',
'			aa.TNO',
'		from Challan aa',
'		where aa.AccountCode = :P242_AccountCode',
'			and aa.MoneyTransferModeCode in (''CH'', ''CHEQUE'')',
'			and aa.MONEYTRANSFERREFERENCENO = b.ChequeNO',
'			and aa.MONEYTRANSFERREFERENCENO  is not null',
'	)		',
'	/*and not exists(',
'		select',
'			aa.TNO',
'		from TDSChallanDetail aa',
'		where aa.AccountCode = :P242_AccountCode',
'			and aa.MoneyTransferModeCode in (''CH'', ''CHEQUE'')',
'			and aa.MONEYTRANSFERREFERENCENO = b.ChequeNO',
'			and aa.MONEYTRANSFERREFERENCENO  is not null',
'	)			',
'	*/',
'	and not exists(',
'		select',
'			aa.TNO',
'		from FreightAdvice aa',
'		where aa.CreditAccountCode = :P242_AccountCode',
'			and nvl(aa.MoneyTransferModeCode, ''fd23S'') in (''CH'', ''CHEQUE'')',
'			and aa.MONEYTRANSFERREFERENCENO = b.ChequeNO',
'			and aa.MONEYTRANSFERREFERENCENO  is not null',
'	)	',
'Order by 1'))
,p_source_type=>'SQL'
,p_location=>'LOCAL'
,p_return_column_name=>'R'
,p_display_column_name=>'D'
,p_version_scn=>'4388337262'
);
wwv_flow_imp.component_end;
end;
/
