prompt --application/pages/page_00038
begin
--   Manifest
--     PAGE: 00038
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2026.03.30'
,p_release=>'26.1.2'
,p_default_workspace_id=>4744311978888504
,p_default_application_id=>107
,p_default_id_offset=>9480203831466364
,p_default_owner=>'IMART'
);
wwv_flow_imp_page.create_page(
 p_id=>38
,p_name=>'Loan Sanction'
,p_step_title=>'Loan Sanction'
,p_autocomplete_on_off=>'OFF'
,p_step_template=>4072355960268175073
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'18'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(469418467356283845)
,p_plug_name=>'Loan Sanction'
,p_static_id=>'loan-sanction'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>2100526641005906379
,p_plug_display_sequence=>10
,p_plug_item_display_point=>'ABOVE'
,p_query_type=>'TABLE'
,p_query_table=>'LOANSANCTION'
,p_include_rowid_column=>false
,p_plug_source_type=>'NATIVE_IR'
,p_prn_page_header=>'638'
,p_ai_enabled=>false
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(469418546809283845)
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_internal_uid=>20953473778119497
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469419232287283890)
,p_db_column_name=>'COMPANYCODE'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Companycode'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469429669483283896)
,p_db_column_name=>'CREATIONTIME'
,p_display_order=>28
,p_column_identifier=>'AB'
,p_column_label=>'Creationtime'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469427603372283895)
,p_db_column_name=>'CREATOR'
,p_display_order=>23
,p_column_identifier=>'W'
,p_column_label=>'Creator'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469425975456283894)
,p_db_column_name=>'CREDITACCOUNTCODE'
,p_display_order=>19
,p_column_identifier=>'S'
,p_column_label=>'Creditaccountcode'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469428068628283895)
,p_db_column_name=>'DEDUCTEDAMOUNT'
,p_display_order=>24
,p_column_identifier=>'X'
,p_column_label=>'Deductedamount'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469424801860283893)
,p_db_column_name=>'DEDUCTIONSTARTDATE'
,p_display_order=>16
,p_column_identifier=>'P'
,p_column_label=>'Deductionstartdate'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469420471558283890)
,p_db_column_name=>'DOCTYPECODE'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Doctypecode'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469419665101283890)
,p_db_column_name=>'FINANCIALYEARCODE'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'Financialyearcode'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469424012398283893)
,p_db_column_name=>'INSTALLMENTAMOUNT'
,p_display_order=>14
,p_column_identifier=>'N'
,p_column_label=>'Installmentamount'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469422827208283893)
,p_db_column_name=>'LOANAMOUNT'
,p_display_order=>11
,p_column_identifier=>'K'
,p_column_label=>'Loanamount'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469422037547283892)
,p_db_column_name=>'LOANREQUESTNO'
,p_display_order=>9
,p_column_identifier=>'I'
,p_column_label=>'Loanrequestno'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469421620456283892)
,p_db_column_name=>'LOANREQUESTTNO'
,p_display_order=>8
,p_column_identifier=>'H'
,p_column_label=>'Loanrequesttno'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469421264199283891)
,p_db_column_name=>'LOANSANCTIONDATE'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Loansanctiondate'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469420800866283890)
,p_db_column_name=>'LOANSANCTIONNO'
,p_display_order=>6
,p_column_identifier=>'F'
,p_column_label=>'Loansanctionno'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469422420149283893)
,p_db_column_name=>'LOANTYPECODE'
,p_display_order=>10
,p_column_identifier=>'J'
,p_column_label=>'Loantypecode'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469420045721283890)
,p_db_column_name=>'LOCATIONCODE'
,p_display_order=>4
,p_column_identifier=>'D'
,p_column_label=>'Locationcode'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469423253483283893)
,p_db_column_name=>'MERGEDAMOUNT'
,p_display_order=>12
,p_column_identifier=>'L'
,p_column_label=>'Mergedamount'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469428851861283895)
,p_db_column_name=>'MODULECODE'
,p_display_order=>26
,p_column_identifier=>'Z'
,p_column_label=>'Modulecode'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469429232971283896)
,p_db_column_name=>'MODULESNO'
,p_display_order=>27
,p_column_identifier=>'AA'
,p_column_label=>'Modulesno'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469428414465283895)
,p_db_column_name=>'MODULETNO'
,p_display_order=>25
,p_column_identifier=>'Y'
,p_column_label=>'Moduletno'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469426383538283894)
,p_db_column_name=>'MONEYTRANSFERMODECODE'
,p_display_order=>20
,p_column_identifier=>'T'
,p_column_label=>'Moneytransfermodecode'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469427261619283895)
,p_db_column_name=>'MONEYTRANSFERREFERENCEDATE'
,p_display_order=>22
,p_column_identifier=>'V'
,p_column_label=>'Moneytransferreferencedate'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469426800846283894)
,p_db_column_name=>'MONEYTRANSFERREFERENCENO'
,p_display_order=>21
,p_column_identifier=>'U'
,p_column_label=>'Moneytransferreferenceno'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469424378329283893)
,p_db_column_name=>'NOOFINSTALLMENT'
,p_display_order=>15
,p_column_identifier=>'O'
,p_column_label=>'Noofinstallment'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469425612757283894)
,p_db_column_name=>'PAYMENTDONE'
,p_display_order=>18
,p_column_identifier=>'R'
,p_column_label=>'Paymentdone'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469425210371283894)
,p_db_column_name=>'REMARK'
,p_display_order=>17
,p_column_identifier=>'Q'
,p_column_label=>'Remark'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469418827324283886)
,p_db_column_name=>'TNO'
,p_display_order=>1
,p_column_identifier=>'A'
,p_column_label=>'Tno'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(469423638143283893)
,p_db_column_name=>'TOTALAMOUNT'
,p_display_order=>13
,p_column_identifier=>'M'
,p_column_label=>'Totalamount'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(469430327820301657)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'209653'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'TNO:COMPANYCODE:FINANCIALYEARCODE:LOCATIONCODE:DOCTYPECODE:LOANSANCTIONNO:LOANSANCTIONDATE:LOANREQUESTTNO:LOANREQUESTNO:LOANTYPECODE:LOANAMOUNT:MERGEDAMOUNT:TOTALAMOUNT:INSTALLMENTAMOUNT:NOOFINSTALLMENT:DEDUCTIONSTARTDATE:REMARK:PAYMENTDONE:CREDITACC'
||'OUNTCODE:MONEYTRANSFERMODECODE:MONEYTRANSFERREFERENCENO:MONEYTRANSFERREFERENCEDATE:CREATOR:DEDUCTEDAMOUNT:MODULETNO:MODULECODE:MODULESNO:CREATIONTIME'
);
wwv_flow_imp.component_end;
end;
/
